version: '3.8'

services:
  stockweb:
    build:
      context: .
    image: stockweb:latest
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    env_file:
      - .env                        # ← 加這行，讓 Compose 自動載入 .env
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
