version: '3.8'

services:
  stockweb:
    # 移除 build，改用遠端映像
    image: oreoxy/stockweb:latest  
    # 如果想每次都重新 pull，加上下面一行（Docker Compose v2+ 支援）
    pull_policy: always  

    depends_on:
      - mongo
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
